### ISSUE TITLE
Wrong links when creating a user on a local cluster

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1018]
After creating a local cluster, doing a `amp -s localhost:50101 user signup`, the login contains direction on how to login, but redirects to the cloud cluster: `amp verify...` It should explicitely give the -s option. The user won't guess.

**Comment by bquenin** [comment]
Actually, it's impossible for `amplifier` to know if it is running locally or not. That's why we have a `PublicAddress` field in amplifier configuration (https://github.com/appcelerator/amp/blob/master/cmd/amplifier/server/configuration.go#L23).
This field is not used today, but we could set it using an environment variable and make the cluster deployment script set this environment variable accordingly. This way, we could update the templates to use the public address.

**Comment by ndegory** [comment]
@bquenin now that we're about to have the environment variable in amplifier, how are we suppose to set it? Should it be in the stackfile?

**Comment by bquenin** [comment]
No specific requirements on how to set it. It just need to be set by the deployment tool.

**Comment by subfuzion** [comment]
Coping my comments from chat:

This is an easy problem to solve when it's HTTP, but my suggestion would be something similar. I'm surprised if gRPC doesn't tell us the address the client connection used to reach the server. I haven't researched to see if we can add message metadata if it isn't already there. We could always add it to the signup message so we then know what address the client used. That would be a more robust way of handling this in my opinion.

**Comment by subfuzion** [comment]
Where there's a will, there's a way!  👍
