### ISSUE TITLE
Cluster management for managed Swarms

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1060]
First, a bit of terminology:
- management swarm: the initial swarm that hosts core services only (amplifier, elasticsearch, kibana, nats, etcd, agent, ampui)
- account swarms: swarm deployed from the management swarm meant to host user stacks / functions.

AMP provides two mechanisms to manage cluster nodes (this document):
- nodes with life cycle managed by AMP (through InfraKit)
  - nodes are created and destroyed based on cluster size requirements, triggered by events (Swarm creation or deletion, scale in or out based on metrics)
- nodes with life cycle managed by the organization (BYOH, see #1144)
  - these nodes are not watched by InfraKit, they should be provisioned by a process outside of AMP

These two types of swarms shouldn't be mixed.

For now we have two deployment options:
- local (docker in docker). For the sake of simplicity we can share core services and user stacks in a single swarm (it's meant for one user, the developer);
- AWS. That initial swarm is only supposed to host the core services. From there, a user can trigger the creation of a new account swarm, with its own set of core services. For billing purposes, that means that the user should provide her own AWS credentials that will be used by the bootstrap / InfraKit to deploy new resources (network resources, EC2 instances).

Most of what is described here can also be applied to a deployment on GCP, once we add this option.

Account swarms should be deployed in their own VPC, because:
- we want to avoid IP exhaustion in the subnets
- a VPC can be created in another AWS account

Running InfraKit in the management Swarm to create a full swarm in another VPC would mean that a configuration file for this swarm has to be maintained on the management swarm, the deployment operations will then consist in modifying this configuration file and deploying it with the help of an InfraKit container, or by running infrakit update operations (scale, etc) directly. The cluster ID will be needed to map the cluster to an account.
The credentials (a key id and a secret key) should only be shared with the InfraKit container (or instance plugin container), so a single container may not be a good idea for security reasons.
To be able to use secrets to share the credentials, InfraKit has to run as a service (global on the managers).
An InfraKit container on the management swarm for each account swarm means a Docker volume (or local mount) for each account swarm.

To make things simple, we can have the same cardinality for the organization and the account swarm, one account swarm for one organization, this way we can deploy the organization Docker registry as part of that swarm. The swarm nodes can then be configured with two registry mirrors: the main one, which contains the ATOMIQ images, and the organization one.

**Comment by bquenin** [comment]
I think it would be better to talk about account swarms instead of user swarms. A user can create a swarm and an organization can create a swarm as well.
Just to clarify, every resource (function, stack) today has an owner. An owner is either a user account (a personal account) or an organization account (a shared account).
I think the same rule applies to a swarm which is just another resource.

**Comment by freignat91** [comment]
if an organization can create an organization then we can keep 1 swarm = organization or user

**Comment by ndegory** [comment]
correct, terminology updated, thanks @bquenin

**Comment by freignat91** [comment]
Then the http requests are routed using account name/id in the host name, at first stage by the haproxy in the management swarm which route to the right haproxy in the user swarm.
So on the user swarm the haproxy doesn't have to deal with account name/id considering it's unique for the user swarm

**Comment by freignat91** [comment]
For the record, minute of the discussion with Nicolas about Elasticsearch (ES) data sharing:
It seems better, instead to have one big ES on the manager swarm which receive all the data (logs, metrics) from all user swarms, to have a dedicated ES on each swarm to store only the data of the swarm.
It makes easier the data management, for instance when we remove a swarm, remove all the data or in term of accounting, the cpu / disc space stay associated to the user swarms is easier to compute than if the data is shared by the manager swarm
however, the API logs and metrics will have to be updated in order to be able to get data from each user swarm using account name and we have to found a way to route api requests to the dedicated ES
