### ISSUE TITLE
Haproxy auto update prototype

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#120]
Prototype of one possible solution:
Use an embeeded controller to have Haproxy configuration updated on ETCD services keys update in push mode (no polling), 
Be able this way to declare any user services as accessible from outside or not
It also should allow to load-balance on several container instances of the services using VIP.

**Comment by freignat91** [comment]
video sent by email to demonstrate the solution
For now i didn't push modifications waiting for consensus/decision.
If it's ok, i'll create a PR on docker-haproxy project

I looked at dockercloud/haproxy and got some idea from there, especially the way HAProxy reload it's configuration, but i didn't found very usable way of working out of docker cloud for now.

**Comment by freignat91** [comment]
Another way to update HAProxy, this time, without ETCD, but still with a embedded controller, is that the controller requests services list using swarm api and update HAProxy accordingly with a given service label to know if a service as to be 'external' or not
The cons is that it's a pull mode and so it needs to request docker swarm api, asking service list on regular basis and it works only on manager nodes.
The pros is that, it doesn't need any third party as ETCD. it relies only on Docker

**Comment by subfuzion** [comment]
Once we're done with our service API, all requests will go through it. The plan is to use etcd to store all stateful information, including publish settings because a developer should be able to use the CLI or website to review (and modify) settings. Since etcd is our global system of record for state, I don't think that bypassing it and polling the swarm directly is a better approach in the larger context. Let's keep using etcd for now, but we can definitely keep this option open.

**Comment by freignat91** [comment]
ok, i prefer too.
