### ISSUE TITLE
Gateway smoke test failing on local swarm deployment

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1207]
`platform/tests/gateway/auth_test.sh` is not passing anymore on local deployments, disabling the test for now.

```
curl -skv --header "Authorization: amp $TOKEN" https://gw.local.atomiq.io/v1/stacks
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to gw.local.atomiq.io (127.0.0.1) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: dashboard.local.atomiq.io
> GET /v1/stacks HTTP/1.1
> Host: gw.local.atomiq.io
> User-Agent: curl/7.51.0
> Accept: */*
> Authorization: amp eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJUeXBlIjoibG9naW4iLCJBY2NvdW50TmFtZSI6InVzZXIiLCJBY3RpdmVPcmdhbml6YXRpb24iOiIiLCJleHAiOjE0OTUyMzA1NDgsImlzcyI6ImFtcGxpZmllciJ9.cHoKOStUE36ZScd_xYCzrXfGYLIO7re3RHB6mkLjcuw
>
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 18 May 2017 21:50:48 GMT
< Content-Length: 10
<
Not Found
* Curl_http_done: called premature == 0
* Connection #0 to host gw.local.atomiq.io left intact
```

**Comment by bquenin** [comment]
This issue seems to only happen on travis, I checked the following:

- unix firewall is disabled: https://travis-ci.org/appcelerator/amp/builds/235845879#L138
- netstat reports the port 443 to listen on all interfaces:https://travis-ci.org/appcelerator/amp/builds/235845879#L696
 - `gw.local.appcelerator.io` nslookup is correctly pointing to 127.0.0.1: https://travis-ci.org/appcelerator/amp/builds/235845879#L712
 - Still it's not possible to connect to the `amplifier-gateway`: https://travis-ci.org/appcelerator/amp/builds/235845879#L723

I'm out of ideas for now :)

**Comment by ndegory** [comment]
what about the proxy status for the gateway? we can query it on http://proxy.local.appcelerator.io:1936
