### ISSUE TITLE
Potential Issue with Root level access to volumes

### ISSUE THREAD

**Issue by chrisccoy** [appcelerator-archive/amp#135]
Here's a simple test that I am able to perform:

```
sudo su -
root@Mister-Christer:~# cd /tmp
root@Mister-Christer:/tmp# mkdir foo
root@Mister-Christer:/tmp# touch foo/this
root@Mister-Christer:/tmp# ls -latd foo; ls -la foo/this
drwxr-xr-x 2 root root 4096 Sep  4 10:39 foo
-rw-r--r-- 1 root root 0 Sep  4 10:39 foo/this
root@Mister-Christer:/tmp# exit
logout
[10:39] chrisccoy@Mister-Christer:tmp $ docker run -it -d -v /tmp:/changeme alpine sh -c "chown -R 1000:1000 /changeme/foo" && ls -latd foo; ls -la foo/this
1bd20e7e24821153a9dfa604369af35e74edc7957f6a80555a7dbb1fb3ca9423
drwxr-xr-x 2 chrisccoy chrisccoy 4096 Sep  4 10:39 foo
-rw-r--r-- 1 chrisccoy chrisccoy 0 Sep  4 10:39 foo/this
```

This appears to essentially give one root level access to any volume mounted in a container. It seems we need a careful examination of how to avoid untoward usage.

**Comment by subfuzion** [comment]
As I commented on #131, I can only imagine right now that this is because you're a member of the `docker` group on your system. If that were not the case, this would be a huge security vulnerability. But as a member of the `docker` group, you don't need to use `sudo` to execute commands that the docker engine runs as `root`. You should easily be able to verify this by removing yourself from the `docker` group (make sure to restart the docker engine). If your example no longer works, then this is not a docker vulnerability, but expected behavior. If it _does_ work, then yeah, this is a _huge_ vulnerability. For what it's worth, as I commented here (https://github.com/appcelerator/amp/pull/131#issuecomment-244620224), this does not work on Docker for Mac

**Comment by subfuzion** [comment]
Closing since this is basically a duplicate of #133. @chrisccoy, go ahead and confirm what happens when you remove yourself from the docker group and just reply in #133. Thanks.
