### ISSUE TITLE
Check system prerequisites for local deployment on linux

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#1446]
Related to #1401

We need to make sure of the following before deploying a local luster on linux:
- `ip_vs` module needs to be loaded (only for DinD deployments).
- `vm.max_map_count` must be greater than 262144.

If these requirements are not met, the local deployment should gracefully abort.

**Comment by JosephGJ** [comment]
Checking for the `ip_vs` modules on a local deployment is not necessary as the local deployment script will initial the swarm node, which will load the `ip_vs` modules anyway. In addition, since we are no longer supporting cluster deployment via DinD, we can remove any documentation on loading the `ip_vs` modules.

**Comment by bquenin** [comment]
@JosephGJ Agreed
