### ISSUE TITLE
Shouldn't be able to set Version and Build via the `amp.yml` config file

### ISSUE THREAD

**Issue by JosephGJ** [appcelerator-archive/amp#1474]
`.config/amp/amp.yml`
```
Version: 0.11.0
Build: randomstring
Server: localhost:50101
Verbose: false
Theme: MyTheme
```
```
$ amp version
[user jgrahamjones @ localhost:50101]
Client:
 Version:       0.11.0
 Build:         randomstring
 Server:        localhost:50101
 Go version:    go1.8
 OS/Arch:       darwin/amd64

Server:
 Version:       v0.12.0-dev
 Build:         659897d0
 Go version:    go1.8.1
 OS/Arch:       linux/amd64
```
Also, `Verbose` value is never used as the cli logger is never used and `Theme` value is never used in `console.go`.

**Comment by bquenin** [comment]
From what I see in the source code, the theme is not configurable and, even if it was, it has no effect since the color defined in the theme are not used in the CLI output.
For verbose mode, it is actually configurable but again, nothing in the code uses this value.
I think the theme feature shouldn't be documented (since it's not working). The Verbose flag shouldn't be documented either since it has no effect.
I'll go ahead and submit a PR so that `Version` and `Build` cannot be overridden.
