### ISSUE TITLE
amp-* go docker images are too fat

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#150]
Our go docker images are around 200Mb each, whereas they should be way smaller.

**Comment by ndegory** [comment]
> $ sudo docker images --format "{{.Repository}} {{.Size}}"
> appcelerator/sut 266.2 MB
> appcelerator/nats-streaming 62.42 MB
> appcelerator/telegraf 102.7 MB
> appcelerator/telegraf 102.7 MB
> appcelerator/amp-agent 745.4 MB
> appcelerator/nats-streaming 62.42 MB
> appcelerator/amp-log-worker 909.4 MB
> appcelerator/amp 1.006 GB
> appcelerator/amp-agent 577.8 MB
> appcelerator/kapacitor 89.4 MB
> appcelerator/haproxy 13.28 MB
> appcelerator/influxdb 116.8 MB
> appcelerator/grafana 159 MB
> nats 7.538 MB
> appcelerator/kibana 179.6 MB
> appcelerator/elasticsearch-amp 179.2 MB
> quay.io/coreos/etcd 43.31 MB
> appcelerator/alpine 48.83 MB
> appcelerator/alpine 50.57 MB

actually, some of them are more than 500MB, almost a GB.
One way to do it would be to use an image to build and just create a from scratch (or from alpine) with just the go binary built on the previous phase. We would drastically reduce the size of the image.

**Comment by subfuzion** [comment]
Yes. It's a very simplistic example of this, but that's exactly what I did with [envtpl](https://github.com/subfuzion/envtpl). I build the binary [here](https://github.com/subfuzion/envtpl/blob/master/make.sh), and just copy it to the image [here](https://github.com/subfuzion/envtpl/blob/master/Dockerfile), so the image that you pull is just a basic alpine image, not the heavier golang one just because it was necessary to compile. The difference in size of the base alpine image vs. the one with the golang toolchain is dramatic:

```
$ docker images | grep -E '(alpine|golang:alpine)'
golang                           alpine              dc6cab1ce719        18 hours ago        241.1 MB
alpine                           latest              4e38e38c8ce0        10 weeks ago        4.799 MB
```

Without golang, the ultimate size of the alpine image with the binary is nice and small:

```
 subfuzion/envtpl                 latest              a120f84ecdc0        4 minutes ago       15.05 MB
```

Note that the compressed size for downloading is only 6 MB:

https://hub.docker.com/r/subfuzion/envtpl/tags/

```
Tag Name      Compressed Size        Last Updated
latest        6 MB                   a minute ago
```
