### ISSUE TITLE
Local deployment should use ampagent

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1591]
the AMP stack deployment on AWS is based on the ampagent (check and install commands).
The local deployment is still based on the older platform/bin/deploy script.
The local deployment should now use the same deployment method as the AWS plugin.

**Comment by ndegory** [comment]
we should then make sure all steps are implemented in the ampagent:
- check the system prerequisites (sysctl)
- initialization of the swarm if it's not already initialized (local mode only)
  - identification of the network interface for the swarm initialization (local mode only)
- add amp.type.* labels if they're missing (local mode only)

the previous method also had the testrunner execution as an option, but I don't think it's a good idea to implement it in the ampagent, it can be ran on Travis as a single command.

**Comment by subfuzion** [comment]
@bquenin Here are the moving parts from the AWS Plugin implementation to match up for local:
* AWS plugin: https://github.com/appcelerator/amp/tree/master/cluster/plugin/aws
* CLI support for running the plugins: https://github.com/appcelerator/amp/blob/master/cli/command/cluster/plugin.go#L162 (currently doesn't run any plugin but calls queryCluster; this should be updated to resemble awsPlugin.Run), https://github.com/appcelerator/amp/blob/master/cli/command/cluster/plugin.go#L162
Let me know if you would like me to walk through anything with you.

@ndegory Thanks for opening the issue for me. However, perhaps I misunderstood the last comment you made, but I do ultimately want the agent to be able to perform all the system checks as part of smoke testing on demand, independent of other environments (eg, travis) and scripts (eg, cloudformation). The goal is that it is responsible for being able to start up the amp backend *and* also able to verify the environment.

However, the other things you mentioned in your previous comment really should be part of the local plugin, not agent plugin. The agent is what we run inside the target cluster for setting up amp after it has been already initially provisioned as we do now with the AWS plugin. This is the extent of the install command's responsibility at the moment: https://github.com/appcelerator/amp/blob/master/cluster/agent/cmd/install.go#L42. There is overlap since the agent should verify the system meets all prerequisites. I prefer to keep the agent as simple as possible and conditional responsibilities to a minimum. Let's chat a bit over a whiteboard session perhaps before anyone starts work on this.

**Comment by ndegory** [comment]
@subfuzion you're right, that first comment content is supposed to be in the local plugin, not in the ampagent, which should focus on the amp stack deployment.

**Comment by subfuzion** [comment]
@bquenin @ndegory Potential local plugin options:  `--local-advertise-addr`, `--local-force-new-cluster`

**Comment by ndegory** [comment]
@subfuzion about the `--local-force-new-cluster`, do you mean the `amp cluster create` should fail if the swarm is already initialized on the local machine? Today it's not the case with the CLI.

**Comment by subfuzion** [comment]
The main idea is that we're creating an amp cluster and for local that just means ensuring swarm mode for a single node (or multiple nodes if we restore our DinD option), then initializing the amp stack. `cluster create` should be symmetric with `cluster rm` ... and for local we don't leave the swarm when we do that, we just tear down amp.

If the swarm hasn't been initialized, then cluster create should do that. But there is no need to "destroy" nodes / leave an existing swarm in the local scenario (unless we restore the DinD option, of course).

We can consider providing an option to leave swarm mode for rm (`cluster rm --local-leave-swarm`), but we definitely don't want to leave swarm mode without the user's explicit consent.

**Comment by ndegory** [comment]
@bquenin for the amp-local plugin to work we need two more things in the ampagent:
- env variables (REGISTRATION and NOTIFICATIONS)
- a new command to remove the amp resources (the stack and the amp_* volumes)
