### ISSUE TITLE
resend verification email

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#1644]
when deploying non locally, a notification is sent to the user for the verification step.
If the notification gets lost, the user can't verify its account.
There should be a command to resend the verification email.

**Comment by JosephGJ** [comment]
Having some issues with adding a new command which sends an email notification. 

Due to #1552 , any email notification command fails, such as `signup` (fixed in #1651)  or `passsword-reset`, because the `ListUser`, `GetUser` and `GetUserByEmail` functions in `store.go` wipe the email using the `secureUser` function. 

So, I cannot get an unverified users email with any of the `user` commands. @bquenin Can I get some consensus on how we can work around this? Currently, you are blocked from seeing an users emails given your authorization, however, a new user should still be able to re-send their verification email to their email account associated with the account they signed up with.

**Comment by bquenin** [comment]
@JosephGJ I think a `GetUserEmail(user *User) string` function in `amp/data/accounts` would solve this issue. It would bypass the email access restriction and would only be called from within amp, i.e. not exposed through the API.
The function would call `getUser` (private method) and return only the associated email or an empty string in case of error.
