### ISSUE TITLE
Impossible to remove a user if the user email is wrong

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#1661]
-1  I create a user freignat with a wrong email myemail@here.com
-2 I can't receive a confirmation email and the user is never verified
-3 i can't delete the user myself to recreate it with the right email because it needs the user to be log in

**Comment by bquenin** [comment]
@freignat91 I think in that case, only `su` is able to remove the user, since we have no way of identifying the requester.

**Comment by ndegory** [comment]
here #1156 would help

**Comment by freignat91** [comment]
@bquenin yes, but for a normal user who don't have su password, it's a shame to have to ask to a super-user.
Better than the user can handle that himself

**Comment by freignat91** [comment]
@ndegory, yes, gc is a way, but then the user have to know when the gc will be executed

**Comment by bquenin** [comment]
@freignat91 it's probably inconvenient, however, if we let anyone delete unverified users, a malicious attacker can deny anyone from signing up by simply delete their accounts continuously.
Probably the best approach would be to delete an unverified user after 1 hour (lifespan of the validation token).

**Comment by freignat91** [comment]
@bquenin, sure, authorize anyone to delete unverified users is not a good solution, but the true user is the only one who know the password he gave, so perhaps we can authorize to delete unverified user but with a password control ?
_(no need to have a new command for that, the 'amp user rm', can be extended to by pass login and ask password if the user wanted to be deleted is not validated)_

**Comment by bquenin** [comment]
@freignat91 what if the unverified user forgets his password?

**Comment by freignat91** [comment]
@bquenin, for password mater the su is there, this time it's the 'normal' way

**Comment by bquenin** [comment]
@freignat91 I'm not convinced it's the best solution. However, you can give it a try :)

**Comment by freignat91** [comment]
@bquenin, it makes no sense to develop a solution we don't agree on. Let's stay on the gc or su ideas so

**Comment by bquenin** [comment]
@freignat91 I don't say it's a bad solution, I'm just thinking of the induced tasks:
 - we need to update the CLI in order to support this parameter,
 - we probably need to update the UI with a dedicated screen for this purpose.
 - In case the unverified user forgets their password, we need to resort to the super user anyway.

The pros are that the user is able to remove themselves from the user DB right away.

It seems that the automatic removal of the user after an hour is less work but the drawback is that the user have to wait an hour before they can sign up again.

It's more a matter of consensus, I personally prefer the gc approach.
