### ISSUE TITLE
Add Persistence to etcd container

### ISSUE THREAD

**Issue by chrisccoy** [appcelerator-archive/amp#278]
# Background

When the swarm restarts, stacks and services that have been previously created are left in an orphaned state, rendering amp cli unable to stop and remove.
# Solution

Add a mount to the etcd swarm command that will cause the etcd `<k,v>` to persist between restarts. 

For example,

```
 --mount type=bind,source=/etcd/data,target=/etcd-data \
    -e ETCD_DATA_DIR=/etcd-data \
```

Thoughts?

**Comment by ndegory** [comment]
@chrisccoy you're right we have to address the persistence, especially for etcd. The issue here is that on a multi node configuration (the default), the local mount won't help unless we have a shared FS on all the swarm cluster.
Without the sharedFS, we already have a Docker volume that should work on a single node without the addition of a mount option. (there's a /data volume in appcelerator/etcd, but we're still using the official etcd image).

**Comment by ndegory** [comment]
To be clear, the mount option of the service create command accepts two modes: bind mount (from host) or volume mount (Docker data volume). The latter is of interest for us, that means the service will create the named volume and reuse it in case the container fails and restarts on same node.
