### ISSUE TITLE
Kafka shutdown/restart at `swarm start` time requires advertise_service to update hosts file

### ISSUE THREAD

**Issue by hadrien-gantzer** [appcelerator-archive/amp#322]
While starting swarm (`swarm start`)

Kafka container fails to run at 1st start-up & requires user to run `sudo advertise_service kafka` once kafka container is actually ready to update `/etc/hosts`

Need to check what can be done to automate correct config to be appended in `/etc/hosts`file

**Observation upon `swarm start`:**
- `$ docker ps -a --format "{{.ID}}  {{.Image}}  {{.Status}}" | grep kafka` will return 2 containers:

> 59dae82a24af  appcelerator/kafka:0.10.0.1  Up 19 minutes (healthy)
> 15b11e69f8f3  appcelerator/kafka:0.10.0.1  Exited (2) 19 minutes ago
- `$ cat /etc/hosts`

> 127.0.0.1 localhost   15b11e69f8f3
- `$ sudo advertise_service kafka`
- `$ cat /etc/hosts`

> 127.0.0.1 localhost   59dae82a24af

**Comment by ndegory** [comment]
PS: the first Kafka container is killed after ~ 55 sec because of a failed healthcheck, 5 failing streaks with the message

```
Health check exceeded timeout (2s)
```

both container take 6sec before the "[Kafka Server 1001], started" message and 12 sec before the "is listening on port :4242" message (admin API), not sure why the healthcheck fails after that.

there's one issue in the healtcheck script: if the ZOOKEEPER_CONNECT env variable is not set, the script will fail. But it's not our case in the swarm script.

**Comment by ndegory** [comment]
at start (maybe because the node has a lot of activities with all the containers starting in parallel), the health.sh script takes more than 2 secs (the timeout of the HEALTHCHECK command). Updating this timeout to 5 sec would probably solve the issue.

**Comment by subfuzion** [comment]
Closing for now since we've switched to NATS. Will reopen if we need to deal with Kafka again.
