### ISSUE TITLE
Move registry data directory

### ISSUE THREAD

**Issue by subfuzion** [appcelerator-archive/amp#351]
Ref: https://github.com/appcelerator/amp/pull/285

The directory should be placed under an `~/.amp` directory; ie, `~/.amp/logs/registry`, or something similar.

**Comment by ndegory** [comment]
@subfuzion we don't need the folder on the host anymore, we use a named volume instead, because:
- no need to make the content available on the host, we don't read or write it from the host
- no need to create the folder on the host
- same function: the volume is kept on the local node and reused next time a container is created 

Ref: #281

**Comment by ndegory** [comment]
issue not relevant anymore, there's no directory created for containers in version 0.2.2 and forthcoming 0.3.0.
