### ISSUE TITLE
swarm script not compatible with system with more than one IP

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#39]
$ sudo ./swarm start --min

> Initializing swarm
> Error response from daemon: could not choose an IP address to advertise since this system has multiple addresses - specify one with --advertise-addr

--advertise-addr is not an option from the swarm script, probably from Docker.

**Comment by subfuzion** [comment]
@ndegory Please show the output from running `docker version`.

**Comment by ndegory** [comment]
$ sudo docker version
[sudo] password for nicolas:
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:40:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:40:59 2016
 OS/Arch:      linux/amd64

I do this on my VM where I have two network interfaces.
I found a workaround: do a docker swarm init --advertise-addr=192.168.56.101 before running the swarm script.

**Comment by subfuzion** [comment]
Sounds good; I thought you meant the `--advertise-addr` option wasn't available to you, which is why I asked for your docker version.

If you look at my [sample for setting up a swarm](https://github.com/appcelerator/docker-example-swarm-bootstrap-local/blob/master/bootstrap#L15) that I shared a couple of weeks ago, you'll see that it also uses `--advertise-addr` for essentially the same reason (there are multiple interfaces available to the machine, so we have to specify the one we want -- obviously the one meant to be accessed externally).

I'll go ahead and close this issue now.
