### ISSUE TITLE
amp stack ls error

### ISSUE THREAD

**Issue by AlexandreDemailly** [appcelerator-archive/amp#499]
'amp stack ls' is not able to display the status "partially running" or "failed" for a stack
When we have a failed stack amp platform monitor display a stack but 'amp stack ls -a' displays 'no stack available'
So we cannot stop it and remove it as we are not able to get its ID.

**Comment by ndegory** [comment]
thank you for the report @AlexandreDemailly 
Can you please provide the version you use (if not a release, which branch or which commit of master branch), and which context (local, cluster, AWS, etc)?

**Comment by freignat91** [comment]
The point is that a amp stack is considered "running" when all of its services have been created, no matter if these services failed after a while.
The fix could be to re-assess the services status when the command "stack ls" is executing for all stack listed in order to be able to display ones reflecting the current reality.
It's related to #411, because "depending on" ask to develop functions able to asses real service status as it has been done for the "amp pf start command". So at the end: have the same behavior for user stack than for the infra stack.

**Comment by bquenin** [comment]
Obsolete, amp doesn't manage stacks anymore
