### ISSUE TITLE
CI ready AMP

### ISSUE THREAD

**Issue by avianey** [appcelerator-archive/amp#503]
**Description**

As a developer leveraging AMP as deployment target, I want to be able to 
1. publish my application(s) as docker images to my private registry
2. create a CI job that deploy a solution over AMP using all my docker components to perform IT tests
3. use a remote AMP deployment to deploy my stack into

For now it is not possible to have the adequate separation of concern. When snapshot image of MS A need to perform IT tests in the context of release images of MS B and C (A, B, C pushed to private registries), I just can't leverage a stack file to deploy a running stack where all MS are pulled from the AMP cluster from the private registry that requires authentication.

**Steps to reproduce the issue:**

1. follow vagrant/README.md of simple-vm-setup branch from engage-amp project 

**Describe the results you received:**

Commands are all OK, but nothing can be pulled from the SWARM cluster.
Also no documentation around this... amp registry push is not working or not documented ???

**Describe the results you expected:**

Any solution that make it work and that is CI friendly...
Pulling release images already in the private registry from the CI runner for pushing them back to the amp cluster **IS NOT** a (long term) solution (=> job will take twice more time, twice more memory, ...)
But I should be able to push temporary image build where the amp cli is for test purpose too (so amp registry push should stay available with a way to clean the AMP registry so it does not grow forever with snapshots or whatever)

* [ ] amp stack up should allow to pass credentials
* [ ] the cluster should be configurable to access any registry
* [ ] I can still push image to the amp registry

**Additional information you deem important (e.g. issue happens only occasionally):**

See branch mentioned above

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   34a2ead
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   34a2ead
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `amp version`:**

```
0.3.0 release
```

**Additional environment details (AWS, etc., if applicable):**

See branch mentioned above

**Comment by generalhenry** [comment]
Registry authentication centers around `~/.docker/config.json`

When you run `docker login` you make an entry there, and when you run `docker run` et al the docker client sends a request to the docker engine, the docker-engine reads `~/.docker/config.json` and then the docker engine sends the credentials to the registry to authenticate.

This all breaks down in a docker swarm since not all the nodes in the swarm will have the same `~/.docker/config.json` in their host fs.  To get around the issue `docker service create` has a `--with-registry-auth` flag which makes the docker client read your local `~/.docker/config.json`, send the credentials to the docker swarm manager, which sends the credentials to the docker engines, which send the credentials to the registry and all is well again.

So my proposal is to add a `--with-registry-auth` flag to `amp service create`, `amp stack create` and `amp stack up` which will cause the amp client to read the local `~/.docker/config.json` send the credentials to amplifier, which will send them to docker swarm . . . such that private registries will simply work so long as the flag is added.
