### ISSUE TITLE
Question on docker-compose

### ISSUE THREAD

**Issue by muhilan** [appcelerator-archive/amp#546]
Will AMP be supporting deploy from a docker-compose in the future? Docker 1.13 will have this feature.

**Comment by generalhenry** [comment]
We've been discussing this internally.  Docker 1.13 adds two things, [docker compose version 3](https://deploy-preview-716--docker-docs.netlify.com/compose/compose-file/) and [docker stack deploy](https://github.com/docker/docker/pull/27998).

docker compose v3 is close to a superset of our stackfile.yaml, however it does not include [routing information](https://github.com/appcelerator/amp/blob/master/docs/stacks-userguide.md#246-public-service-item)

`docker stack deploy` is a bit different than `amp stack up` since amp stacks persist in the data store when stopped.

Going forward we're looking into incorporating both into amp.

**Comment by muhilan** [comment]
Thanks @generalhenry .
