### ISSUE TITLE
User Story: service links

### ISSUE THREAD

**Issue by generalhenry** [appcelerator-archive/amp#597]
I'm an amp user and I my team has some stacks running.  I know that my services are published but I don't know the urls.  I want a command that list the urls and/or the urls to be listed in the ui.

Proposed interface:
`amp stack links [stack_ident . . .]`
```
http://{{spec}}.{{stack}}.local.atomiq.io/
http://{{spec}}.{{stack}}.local.atomiq.io/
http://{{spec}}.{{stack}}.local.atomiq.io/
. . .
```

**Comment by subfuzion** [comment]
Wow, it only took you two minutes to implement! ;)

**Comment by subfuzion** [comment]
I like it. My only objection is a bit pedantic regarding the term "link", which I generally use in a clickable context (eg, web page links) ... otherwise I think telecommunication/network links. I'm not so pedantic that I insist on using URI, and I don't want to bikeshed over this, but can we get maybe one or two more opinions for consensus around this? On the plus side, "links" rolls off the tongue slightly easier than "addresses" and "urls". Still, my preference would be for "urls", which even you used in the user story narrative itself.

**Comment by generalhenry** [comment]
So `amp stack urls [stack_ident]`?

**Comment by subfuzion** [comment]
I'm not adamant about it, but yes, I do think that's better. Do you want to get a tie-breaking opinion, or do you not feel strongly about it. Other than that, this is a very good thing to add.

**Comment by generalhenry** [comment]
I just had links on my mind since I implemented the web-ui first

**Comment by ndegory** [comment]
```urls``` is good

**Comment by subfuzion** [comment]
Actually, I like `amp stack routes <stack>`, which to me is more representative I what I want to know about the stack. (It's ok that it's the full url route)

**Comment by ndegory** [comment]
what about ```urls``` with a ```route``` alias?

**Comment by subfuzion** [comment]
Let's just pick one.

**Comment by subfuzion** [comment]
We are going to start bikeshedding, aren't we, lol. Well, we are using haproxy for our url-based 
routing ;)

**Comment by subfuzion** [comment]
@generalhenry , make the call and we'll live with it for now. 👊
