### ISSUE TITLE
Ineffective cluster management through corporate firewalls

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#666]
amp CLI uses a commonly open port (8080) so it's usable behind a corporate network.
ampadm CLI uses a non standard port (31315) which is most probably blocked.
As a consequence, it's impossible to manage a remote cluster.

**Comment by subfuzion** [comment]
We really only want to use 443 for web UI over HTTPS, and gRPC REST gateway APIs we support. All our normal gPRC service communications, eg, CLI to backend can remain over 50101. 80/443/8080 is for normal http traffic. gRPC uses HTTP/2 framing underneath, but the services we expose are not for typical HTTP request-response messaging.

I chose 50101 for amp because I figured it's in a nice safe range and we can have a block of non-standard ports in a series as needed by the platform (50101...501XX).
