### ISSUE TITLE
Kafka is not reachable from amplifier

### ISSUE THREAD

**Issue by bquenin** [appcelerator-archive/amp#69]
Amplifier is connecting to kafka through localhost:9092.
However, this hostname is used only for the first connection to kafka. On this first call, kafka gives its own hostname to the client (amplifier).
The problem is that the hostname given by kafka (which is actually the kafka container short id) is not reachable from amplifier because it's not part of amp-swarm network.

Possible fixes:
- Running amplifier as a container and make it part of the amp-swarm network using `docker run` , however services and containers cannot be part of the same network.

```
docker run --network amp-swarm appcelerator/amp
docker: Error response from daemon: swarm-scoped network (amp-swarm) is not compatible with `docker create` or `docker run`. This network can only be used by a docker service.
See 'docker run --help'.
```
- Giving the service a hostname, however, I don't think it's possible:

```
docker service create --help

Usage:  docker service create [OPTIONS] IMAGE [COMMAND] [ARG...]

Create a new service

Options:
      --constraint value               Placement constraints (default [])
      --container-label value          Container labels (default [])
      --endpoint-mode string           Endpoint mode (vip or dnsrr)
  -e, --env value                      Set environment variables (default [])
      --help                           Print usage
  -l, --label value                    Service labels (default [])
      --limit-cpu value                Limit CPUs (default 0.000)
      --limit-memory value             Limit Memory (default 0 B)
      --log-driver string              Logging driver for service
      --log-opt value                  Logging driver options (default [])
      --mode string                    Service mode (replicated or global) (default "replicated")
      --mount value                    Attach a mount to the service
      --name string                    Service name
      --network value                  Network attachments (default [])
  -p, --publish value                  Publish a port as a node port (default [])
      --replicas value                 Number of tasks (default none)
      --reserve-cpu value              Reserve CPUs (default 0.000)
      --reserve-memory value           Reserve Memory (default 0 B)
      --restart-condition string       Restart when condition is met (none, on-failure, or any)
      --restart-delay value            Delay between restart attempts (default none)
      --restart-max-attempts value     Maximum number of restarts before giving up (default none)
      --restart-window value           Window used to evaluate the restart policy (default none)
      --stop-grace-period value        Time to wait before force killing a container (default none)
      --update-delay duration          Delay between updates
      --update-failure-action string   Action on update failure (pause|continue) (default "pause")
      --update-parallelism uint        Maximum number of tasks updated simultaneously (0 to update all at once) (default 1)
  -u, --user string                    Username or UID
      --with-registry-auth             Send registry authentication details to swarm agents
  -w, --workdir string                 Working directory inside the container
```
- Running amplifier as a service: It's definitely possible, however, it's not compatible with development where you need to be able to quickly launch, fix, and repeat. Indeed, docker services are not using local images but instead pull images from the hub (or a private registry) on each start (check this issue https://github.com/docker/swarmkit/issues/1246). It would require to push, build and publish the image every time which defeats the purpose.

The only workaround I found so far is to add kafka container hostname to `/etc/host`:
Getting kafka hostname:

```
docker ps
docker inspect kafka_container_id | grep hostname
sudo cat /var/lib/docker/containers/a4424bcafbab110b67922994243aca15fc57ab3422fdec21f7460fe16b024456/hostname
```

Update /etc/hosts in order to assign 127.0.0.1 to kafka hostname:

```
127.0.0.1   localhost a4424bcafbab
```

**Comment by subfuzion** [comment]
@bertrand-quenin Great write up of the problem, thanks.

Unfortunately the following doesn't work for Docker for Mac:

```
sudo cat /var/lib/docker/containers/a4424bcafbab110b67922994243aca15fc57ab3422fdec21f7460fe16b024456/hostname
```

On Docker for Mac these files are stored in the VM located here:

```
$HOME/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
```

But since it looks like the hostname is just the short-id anyway, I think this will work (at least for our temporary workaround right now):

```
docker ps --filter "name=kafka\." --format '{{ .ID }}'
```

(The funky filter is to eliminate `kafka-manager` from the result, so for example only `kafka.1.0vouaqq9cb6xgileqju2q9m78`, not `kafka-manager.1.beyw2nt38n4556s9qacaw16ew`).

I'll test that out and report my results back here shortly.

**Comment by subfuzion** [comment]
We need a better interim strategy; asking everyone to help brainstorm on this. There must be some way (I hope) to set the hostname that kafka advertises to clients, whether a configuration, environment variable, flag, etc. That would mean there is some way we can customize the image to make it so we can set it dynamically (if it's a static configuration setting somewhere). Then we can make kafka advertise `localhost` or `127.0.0.1` on our local machines...

**Comment by subfuzion** [comment]
It seems like `advertised.listeners` might be what we're looking for in the Broker Configs [docs](http://kafka.apache.org/documentation.html#brokerconfigs)... would it be possible to make it advertise `localhost` for local development instead of the container hostname?

@bertrand-quenin @ndegory Can you two investigate further and see if you can come up with a strategy?

**Comment by subfuzion** [comment]
@bertrand-quenin @ndegory Can you two investigate further?

**Comment by subfuzion** [comment]
Regarding my last comment, I don't think the issue is advertising the hostname, it's making sure the hostname is available outside the swarm's network when we're developing ...

**Comment by subfuzion** [comment]
I suppose this is where kafka updates and then gets the server address for subsequent requests on the client broker:

https://github.com/Shopify/sarama/blob/master/broker.go#L83
https://github.com/Shopify/sarama/blob/master/broker.go#L161

**Comment by bquenin** [comment]
@subfuzion Actually, I already tried this solution. It effectively makes kafka reachable from amplifier by advertising `localhost`. The problem is that other components (telegraf, amp-log-worker) are trying to reach kafka on localhost as well ... making them fail miserably.

**Comment by subfuzion** [comment]
@bertrand-quenin Unfortunately, that makes perfect sense. Please brainstorm with @ndegory to find a solution. I also asked for help with this on the Docker Captains slack channel, so hopefully will hear back from someone soon. Thanks!

**Comment by subfuzion** [comment]
We may have to create a script that can take the output of `docker ps --filter "name=kafka\." --format '{{ .ID }}'` and update the entry for `127.0.0.1` in /etc/hosts. We can call the script from the swarm script when we start up the swarm. @ndegory, we're all slammed preparing for our deadline on Monday; is there any way you can take this on for us?

**Comment by ndegory** [comment]
I'll take a look

**Comment by subfuzion** [comment]
@bertrand-quenin Now that I think about it, can't we override the address in the client after it gets updated with the server's metadata, just to ensure we're using the address we want to use? After all, in the real swarm we would want to use the actual DNS name (`kafka`) anyway since swarm is load balancing for us. There isn't some special requirement for affinity to a particular server in the cluster, is there?

**Comment by subfuzion** [comment]
Thanks for the [PR](https://github.com/appcelerator/amp/pull/82), @ndegory. It's working well for now. I'll leave this issue open while we consider our long term strategy for this and similar/related issues.

**Comment by freignat91** [comment]
There is another solution which do not imply to modify /etc/host:
If we have amplifier inside swarm network it works as explains above, but then the issue is that we can't build locally an amplifier image to test.
Except, for the test need, if we modify the amplifier image name 'appcelerator/amp' to 'appcelerator/amp_fr (for instance for me) and modify the swarm file to point on this image name instead of the normal.
The amp_fr image is never save on repo. It exists only locally.
Then, all work, docker see that appcelerator/amp_fr doesn't exist in repo and use the local image
It how I do for amp-ui for instance or amp-agent when i don't want to modify the repo, but i want to have my own an updated images for test. It works well.

**Comment by subfuzion** [comment]
@bertrand-quenin Can you respond to https://github.com/appcelerator/amp/issues/69#issuecomment-242868643?

**Comment by bquenin** [comment]
Yes, it's an alternate solution to this issue. It can work as well.

**Comment by subfuzion** [comment]
@freignat91 @bertrand-quenin @ndegory Since I prefer that we switch to NATS, I'm not particularly concerned about the long term resolution for this particular issue at this point. However, it is definitely the case that `amplifier` will eventually expose its services on an overlay network (for example, `amp-swarm-public`), and it will also overlap with the backbone network (`amp-swarm`) to communicate with our infrastructure services. @freignat91, we should start moving toward this configuration this sprint, and also start incorporating haproxy for mapping exposed IPs to consumers (eg, the CLI).

**Comment by subfuzion** [comment]
It's interesting to be aware of how clusters and node discovery impact other services for client communication as well. For example, the etcd client when etcd is behind a load-balanced cluster: https://github.com/hashicorp/vault/pull/921.

**Comment by subfuzion** [comment]
Since we have a working solution in place for now thanks to @ndegory and our priority has shifted to transitioning to NATS (#113), I'm going to close this.
