### ISSUE TITLE
AMP displays logs from all containers, even ones not part of a stack

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#932]
`amp logs` display the logs of the infrakit container, and probably all containers running on the Swarm nodes.
Not sure if it's a feature or a bug, but at least we should be able to filter them out.

**Comment by bquenin** [comment]
For now, we capture everything on the swarm. @subfuzion please advise

**Comment by freignat91** [comment]
yes, every logs are read by the agent and sent to nats. We could imagine have a special container label, as "amp.nologs" to do not log specific containers?

**Comment by subfuzion** [comment]
For now, `logs -i` should only show infrastructure nodes as pertaining to the core cluster that is created to host the swarm (including the registry node) - my original bootstrap script labeled these with `host.role=cluster` plus separate `node.role=swarm` to distinguish and filter specifically on swarm nodes only. I have no problem considering the infrakit containers to be an integral part of the cluster since they're there to manage and heal nodes and right now there's no other access to their logs. However, we can create more labels to help discriminate and filter what we want to see and, ultimately, viewing these logs will require admin authorization and probably require the use of `amp cluster logs`, not `amp logs -i`.

**Comment by bquenin** [comment]
Sure, maybe we can add the `infrastucture` label to infrakit containers in the meantime. This way they'll be excluded from the default log output until we enhance our commands.

**Comment by bquenin** [comment]
@ndegory AMP collects all logs by design, using adequate filters should be enough
