### ISSUE TITLE
HA for deployment tool

### ISSUE THREAD

**Issue by ndegory** [appcelerator-archive/amp#944]
Right now the InfraKit container runs only on one manager and uses the OS mode to manage it's plugins.
InfraKit is able to run on all 3 managers and use the Swarm annotations to share the deployment state across the nodes.
Once implemented in our deployment scripts, we should check that the loss of a manager node leads to the election of a new InfraKit leader (as well as a new Swarm manager leader), and that when the missing manager is reestablished it is correctly incorporated in the cluster (Swarm manager and Infrakit, both non leader).

**Comment by JosephGJ** [comment]
This is possible to do using `infrakit-manager swarm` functionality which allows for the synchronization of the infrakit leaders with the docker swarm leaders. Along with this, the election process of the new leader (in the case that the leader goes down) involves freeing any groups managed by the current swarm leader infrakit node and committing them to the new leader. 

However, because we are using terraform to manage the health of the instances within the recommitted groups, the `.tfstate` files that are generate on the original m1 node are not moved over to the new leader in the instance that m1 is terminated, and so the health of the worker group can no longer managed by infrakit.
