### ISSUE TITLE
ampmake build-cli doesn't generate amp binary on mac anymore

### ISSUE THREAD

**Issue by freignat91** [appcelerator-archive/amp#958]
- `ampmake clean build-cli`
- amp -> .../dev/go/src/github.com/appcelerator/amp/bin/darwin/amd64/amp: No such file or directory

- `make clean build-cli` generate it

**Comment by JosephGJ** [comment]
I believe this happens because `ampmake` runs the `amptools` container so when the `$GOOS` command is run it fetches `amptools` os rather than the systems os. The `make clean build-cli` command doesn't use `ampmake` and the `buildall-cli` is called in `ampmake check` rather than `build-cli`.

**Comment by subfuzion** [comment]
This is not a bug. As mentioned in https://github.com/appcelerator/amp/pull/926, if you build in a container environment (using `ampmake`), you need to use `buildall-cli` right now to build all cross-compiled versions of the cli.

The `build-cli` rule is specifically dedicated right now as an optimization for working on cli commands. You can run `make build-cli`, and it will build a version correctly for your platform (it uses go to determine $GOOS from the environment). When you run make inside of the amptools container, then $GOOS will be the OS that the amptools container uses (it's currently based on an ubuntu image).

We could add a few more specific cross-compilation target rules (eg, `build-cli-darwin`) that would be guaranteed to work from `ampmake` -- so $GOOS would be specified instead of determined from the environment. But we don't have time at the moment, so please use `ampmake build|buildall|buildall-cli|check`) when you want to guarantee the cross-compiled versions are built. When you're hacking on the CLI itself, just run `make build-cli` as a quick way of building until you're ready to run `ampmake check` and submit your PR.

**Comment by subfuzion** [comment]
@JosephGJ Your analysis is correct!

**Comment by freignat91** [comment]
ok, thanks Tony, i close this issue
